(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var l;function m(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function p(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:m(a)}}var q="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},r;
if("function"==typeof Object.setPrototypeOf)r=Object.setPrototypeOf;else{var t;a:{var v={l:!0},w={};try{w.__proto__=v;t=w.l;break a}catch(a){}t=!1}r=t?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var x=r;
function y(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function z(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a};function A(){}var B="function"==typeof Uint8Array,C=[];function D(a,b){if(b<a.c){b+=a.h;var c=a.a[b];return c===C?a.a[b]=[]:c}if(a.b)return c=a.b[b],c===C?a.b[b]=[]:c}function E(a,b){a=D(a,b);return null==a?"":a}function F(a,b){a=D(a,b);a=null==a?a:!!a;return null==a?!1:a}A.prototype.toString=function(){return this.a.toString()};function G(){}G.prototype.j=function(){};function H(a){this.b=a;this.c="x-"+this.b+"-l";this.a=this.b+"-l-"};function I(a){return Error("MysidiaJsError["+a+"] ")};function J(a){a||(a=[]);this.h=-1;this.a=a;a:{if(a=this.a.length){--a;var b=this.a[a];if(!(null===b||"object"!=typeof b||"array"==y(b)||B&&b instanceof Uint8Array)){this.c=a- -1;this.b=b;break a}}this.c=Number.MAX_VALUE}}z(J,A);function K(a){return(a=L(a,"monitor"))?new J(a?JSON.parse(a):null):null}function L(a,b){a=a.getElementsByTagName("META");for(var c=0;c<a.length;++c)if(a[c].getAttribute("name")===b)return a[c].getAttribute("content");return""};var M=["googqscp","osdlfm"];
function N(){var a=this;this.b=this.a=null;this.o=this.v.bind(this);this.m=function(c){if(!a.a)throw I(63);c.detail&&a.a("send","exception",{exDescription:c.detail.message,exFatal:!1})};this.h={};var b={};this.c=(b.overallReady=this.u.bind(this),b.overallQuiet=this.s.bind(this),b.overallError=this.i.bind(this,"oe"),b.assembleStart=this.g.bind(this,"ea"),b.assembleReady=this.f.bind(this,"ea"),b.decorateStart=this.g.bind(this,"ed"),b.decorateReady=this.f.bind(this,"ed"),b.fontStart=this.g.bind(this,
"wf"),b.fontReady=this.f.bind(this,"wf"),b.spanStart=this.g.bind(this,"ws"),b.spanReady=this.f.bind(this,"ws"),b.prepareStart=this.g.bind(this,"dp"),b.prepareReady=this.f.bind(this,"dp"),b.bindingStart=this.g.bind(this,"dd"),b.bindingReady=this.f.bind(this,"dd"),b.browserStart=this.g.bind(this,"bs"),b.browserStartEnd=this.f.bind(this,"bs"),b.browserReady=this.g.bind(this,"br"),b.browserReadyEnd=this.f.bind(this,"br"),b.browserQuiet=this.g.bind(this,"bq"),b.browserQuietEnd=this.f.bind(this,"bq"),b)}
N.prototype=q(G.prototype);N.prototype.constructor=N;if(x)x(N,G);else for(var O in G)if("prototype"!=O)if(Object.defineProperties){var P=Object.getOwnPropertyDescriptor(G,O);P&&Object.defineProperty(N,O,P)}else N[O]=G[O];l=N.prototype;
l.j=function(a){var b=this;if(this.a=window[window.GoogleAnalyticsObject])if(this.b=K(a)){var c=F(this.b,6),e=F(this.b,7);if(c||e){if(!this.a)throw I(63);this.a("create","UA-66202210-1",{siteSpeedSampleRate:100,storage:"none"});this.a("set","dimension1",E(this.b,3));this.a("set","dimension2",E(this.b,2));this.a("set","dimension4",E(this.b,5));this.a("set","transport","beacon");this.a("set","transportUrl","https://www.google-analytics.com/csi/batch");this.a("send","pageview","/");e&&(window.addEventListener("error",
this.o),a.addEventListener("customError",this.m));a.addEventListener("browserReady",function(){var h=L(a,"namespace");if(h){h=new H(h);for(var u=p(a.children),d=u.next();!d.done;d=u.next()){var k=d.value;d=k.getAttribute(h.c);if(!d&&k.className){k=p(k.className.split(" "));for(var f=k.next();!f.done;f=k.next())if(f=f.value,0==f.indexOf(h.a)){d=f.substr(h.a.length);break}}if(d){b.a("set","dimension3",d);return}}}b.a("set","dimension3","NotFound")});if(c&&window.performance&&window.performance.now){for(var g in this.c)a.addEventListener(g,
this.c[g]);this.i("os")}}}};
function Q(a,b,c,e){if(null!=window.performance&&null!=window.performance.getEntries&&null!=window.PerformanceNavigationTiming&&null!=window.PerformanceResourceTiming){for(var g=window.performance.getEntries(),h=0,u=0,d=0,k=0,f=0;f<g.length;++f){var n=g[f];if(n instanceof window.PerformanceNavigationTiming)h+=n.transferSize||0;else if(n instanceof window.PerformanceResourceTiming){var T=n.initiatorType;n=n.transferSize||0;if(0==b.length||0<=b.indexOf(T))d++,u+=0==n?1:0,k+=n}}b=E(a.b,2);e&&a.a("send",
"event",b,"page","bytes",h);a.a("send","event",b,c,"bytes",k);a.a("send","event",b,c,"reqs",d);a.a("send","event",b,c,"caches",u)}}l.u=function(){if(!this.a)throw I(63);Q(this,["script"],"js",!0);this.i("or")};l.s=function(a){if(!this.a)throw I(63);Q(this,[],"res",!1);this.i("oq");a=a.currentTarget;for(var b in this.c)a.removeEventListener(b,this.c[b])};
l.v=function(a){if(!this.a)throw I(63);for(var b=a.message||"",c=!1,e=0;e<M.length;++e){var g=M[e];if(0<=b.indexOf(g)){b=g;c=!0;break}}b=a.type+": "+b;!c&&a.lineno&&a.colno&&(b+=" at "+a.lineno+":"+a.colno);this.a("send","exception",{exDescription:b,exFatal:!1})};l.i=function(a){R(this,a,window.performance.now())};l.g=function(a){this.h[a]=window.performance.now()};l.f=function(a){this.h.hasOwnProperty(a)&&R(this,a,window.performance.now()-this.h[a])};
function R(a,b,c){if(!a.a)throw I(63);if(!a.b)throw I(64);var e=E(a.b,2),g=E(a.b,3);a.a("send","timing",e,g+b,Math.round(Math.min(c,6E4)))};var S=document.getElementById("mys-content");if(S){var U=new N;S.addEventListener("overallStart",function(){U.j(S)})};}).call(this);
